// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    $('#delete_button').on('click', function(event) {
      if (!confirm('Are you really want delete this message?')) {
        return false;
      }
    });
    return $('.message-edit select').uniform();
  });

}).call(this);
