// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var content_part, form, loading_container, selector;
    loading_container = $('#loading_message');
    content_part = $('#content_part');
    selector = $('#action_selector');
    form = $('#action_select_form');
    selector.uniform();
    return selector.on('change', function(event) {
      var request;
      request = $.ajax({
        url: '/a/get_ajax_messages',
        type: 'post',
        data: form.serialize()
      });
      loading_container.show();
      return request.done(function(response) {
        loading_container.hide();
        return content_part.html(response);
      });
    });
  });

}).call(this);
