// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var item, selects, _i, _len, _results;
    selects = $('#ugc_requests .reasons_selector');
    _results = [];
    for (_i = 0, _len = selects.length; _i < _len; _i++) {
      item = selects[_i];
      _results.push($(item).change(function() {
        var display;
        if ($(this).val() === '...') {
          display = 'block';
        } else {
          display = 'none';
        }
        return $(this).next().css({
          'display': display
        });
      }));
    }
    return _results;
  });

}).call(this);
