// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var baselink, checkbox, guild_name, links;
    checkbox = $('#join_guild');
    links = $('a.reg-link');
    guild_name = $('#guild_name').html();
    baselink = '/registration?' + $('#player_name').html();
    if (checkbox) {
      return checkbox.on('change', function(event) {
        var link, _i, _item, _len, _results;
        link = baselink;
        if (checkbox.is(':checked')) {
          link = link + '&guild=' + guild_name;
        }
        _results = [];
        for (_i = 0, _len = links.length; _i < _len; _i++) {
          _item = links[_i];
          _results.push($(_item).attr('href', link));
        }
        return _results;
      });
    }
  });

}).call(this);
